title: Bangla Kobita Data Lake
author: Mossaddeque Mahmood
description: >-
  Bangla Kobita Data Lake

baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  kobita:
